arb-dir: lib/app/l10n
template-arb-file: app_en.arb
output-dir: lib/app/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated.txt
